const REPORTS = {
  SET_REPORTS: "REPORTS.SET_REPORTS",
  GET_BY_DATE: "REPORTS.GET_BY_DATE",
  GET_BY_USER: "REPORTS.GET_BY_USER",
  DIAGNOSES: "REPORTS.DIAGNOSES",
  TREATMENTS: "REPORTS.TREATMENTS",
  LENGTH_OF_TRIAL: "REPORTS.LENGTH_OF_TRIAL",
  GET_PATIENTS: 'REPORTS.GET_PATIENTS'
};

export { REPORTS };
